# Generated by Django 2.2.4 on 2019-08-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_showuserprofile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_business', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('delivery_type', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account_number', models.IntegerField(max_length=100)),
                ('branch', models.CharField(max_length=250)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.UserProfile')),
            ],
        ),
    ]
